apiVersion: v1
kind: Service
metadata:
  name: tabpyjlab
  labels:
    app: tabpyjlab
spec:
  type: LoadBalancer
  ports:
  - name: tabpy
    protocol: TCP
    port: 9004    
    targetPort: 9004
  - name: jlab
    protocol: TCP
    port: 8888
    targetPort: 8888
  selector:
    app: tabpyjlab
